CREATE DATABASE IF NOT EXISTS songwriters_toolkit;
USE songwriters_toolkit;

CREATE TABLE IF NOT EXISTS songs (
  id VARCHAR(36) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lyrics (
  id VARCHAR(36) PRIMARY KEY,
  song_id VARCHAR(36) NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  content TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Audio tracks are stored locally, only metadata synced
CREATE TABLE IF NOT EXISTS tracks (
  id VARCHAR(36) PRIMARY KEY,
  song_id VARCHAR(36) NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  type ENUM('backing', 'vocal', 'instrument') NOT NULL,
  filename VARCHAR(255) NOT NULL,
  duration_ms INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
